<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
    public function up(): void
    {
        $guard = function (string $table, \Closure $create) {
            if (!Schema::hasTable($table)) {
                Schema::create($table, $create);
            }
        };
        $guard('users', function (Blueprint $table) {$table->id(); $table->string('name'); $table->string('email')->unique(); $table->timestamp('email_verified_at')->nullable(); $table->string('password'); $table->boolean('is_admin')->default(false); $table->boolean('is_staff')->default(false); $table->boolean('is_active')->default(true); $table->string('phone')->nullable(); $table->rememberToken(); $table->timestamps();});
        $guard('password_reset_tokens', function (Blueprint $table) {$table->string('email')->primary(); $table->string('token'); $table->timestamp('created_at')->nullable();});
        $guard('sessions', function (Blueprint $table) {$table->string('id')->primary(); $table->foreignId('user_id')->nullable()->index(); $table->string('ip_address',45)->nullable(); $table->text('user_agent')->nullable(); $table->longText('payload'); $table->integer('last_activity')->index();});
        $guard('personal_access_tokens', function (Blueprint $table) {$table->id(); $table->morphs('tokenable'); $table->string('name'); $table->string('token',64)->unique(); $table->text('abilities')->nullable(); $table->timestamp('last_used_at')->nullable(); $table->timestamp('expires_at')->nullable(); $table->timestamps();});
        $guard('tournaments', function (Blueprint $table) {$table->id(); $table->string('name'); $table->string('slug')->unique(); $table->string('status')->default('draft')->index(); $table->bigInteger('entry_fee_minor')->default(0); $table->bigInteger('prize_pool_minor')->default(0); $table->integer('max_teams')->default(16); $table->timestamp('starts_at')->nullable(); $table->timestamp('ends_at')->nullable(); $table->json('metadata')->nullable(); $table->timestamps();});
        $guard('wallets', function (Blueprint $table) {$table->id(); $table->foreignId('user_id')->constrained()->cascadeOnDelete(); $table->string('currency',3)->default('BDT'); $table->bigInteger('balance_minor')->default(0); $table->boolean('is_locked')->default(false); $table->timestamps(); $table->unique(['user_id','currency']); $table->index('user_id');});
        $guard('ledger_entries', function (Blueprint $table) {$table->id(); $table->foreignId('wallet_id')->constrained()->cascadeOnDelete(); $table->foreignId('user_id')->constrained()->cascadeOnDelete(); $table->string('direction')->index(); $table->bigInteger('amount_minor'); $table->bigInteger('balance_after_minor'); $table->string('reference_type')->nullable()->index(); $table->string('reference_id')->nullable()->index(); $table->string('idempotency_key')->nullable()->unique(); $table->json('metadata')->nullable(); $table->timestamps(); $table->index(['wallet_id','created_at']);});
        $guard('payments', function (Blueprint $table) {$table->id(); $table->foreignId('user_id')->constrained()->cascadeOnDelete(); $table->foreignId('wallet_id')->nullable()->constrained()->nullOnDelete(); $table->string('provider')->index(); $table->string('external_id')->unique(); $table->string('provider_reference')->nullable()->unique(); $table->bigInteger('amount_minor'); $table->string('currency',3)->default('BDT'); $table->string('status')->default('created')->index(); $table->string('idempotency_key')->unique(); $table->string('idempotency_fingerprint')->nullable(); $table->json('metadata')->nullable(); $table->timestamp('authorized_at')->nullable(); $table->timestamp('succeeded_at')->nullable(); $table->timestamp('failed_at')->nullable(); $table->timestamps(); $table->index(['user_id','created_at']);});
        $guard('payouts', function (Blueprint $table) {$table->id(); $table->foreignId('user_id')->constrained()->cascadeOnDelete(); $table->foreignId('tournament_id')->nullable()->constrained()->nullOnDelete(); $table->bigInteger('amount_minor'); $table->string('currency',3)->default('BDT'); $table->string('status')->default('pending')->index(); $table->string('external_id')->unique(); $table->string('provider')->default('manual'); $table->string('idempotency_key')->unique(); $table->json('metadata')->nullable(); $table->timestamps();});
        $guard('webhook_events', function (Blueprint $table) {$table->id(); $table->string('provider')->index(); $table->string('event_type')->nullable()->index(); $table->string('event_id')->unique(); $table->json('payload')->nullable(); $table->string('signature')->nullable(); $table->string('state')->default('received')->index(); $table->integer('attempts')->default(0); $table->text('last_error')->nullable(); $table->timestamp('processed_at')->nullable(); $table->timestamps(); $table->index(['provider','state']);});
        $guard('idempotency_records', function (Blueprint $table) {$table->string('key')->primary(); $table->string('fingerprint'); $table->string('operation')->index(); $table->foreignId('user_id')->nullable()->constrained()->nullOnDelete(); $table->json('request_body')->nullable(); $table->json('response_body')->nullable(); $table->integer('status_code')->nullable(); $table->timestamp('expires_at')->nullable(); $table->timestamps();});
        $guard('financial_settlements', function (Blueprint $table) {$table->id(); $table->foreignId('tournament_id')->constrained()->cascadeOnDelete(); $table->bigInteger('total_amount_minor'); $table->string('currency',3)->default('BDT'); $table->string('status')->default('pending')->index(); $table->string('idempotency_key')->unique(); $table->json('metadata')->nullable(); $table->timestamp('completed_at')->nullable(); $table->timestamps();});
        $guard('cache', function (Blueprint $table) {$table->string('key')->primary(); $table->mediumText('value'); $table->integer('expiration');});
        $guard('cache_locks', function (Blueprint $table) {$table->string('key')->primary(); $table->string('owner'); $table->integer('expiration');});
        $guard('jobs', function (Blueprint $table) {$table->id(); $table->string('queue')->index(); $table->longText('payload'); $table->unsignedTinyInteger('attempts'); $table->unsignedInteger('reserved_at')->nullable(); $table->unsignedInteger('available_at'); $table->unsignedInteger('created_at');});
        $guard('job_batches', function (Blueprint $table) {$table->string('id')->primary(); $table->string('name'); $table->integer('total_jobs'); $table->integer('pending_jobs'); $table->integer('failed_jobs'); $table->longText('failed_job_ids'); $table->mediumText('options')->nullable(); $table->integer('created_at'); $table->integer('cancelled_at')->nullable(); $table->integer('finished_at')->nullable();});
        $guard('failed_jobs', function (Blueprint $table) {$table->id(); $table->string('uuid')->unique(); $table->text('connection'); $table->text('queue'); $table->longText('payload'); $table->longText('exception'); $table->timestamp('failed_at')->useCurrent();});
    }
    public function down(): void
    {
        Schema::dropIfExists('financial_settlements'); Schema::dropIfExists('idempotency_records'); Schema::dropIfExists('webhook_events'); Schema::dropIfExists('payouts'); Schema::dropIfExists('payments'); Schema::dropIfExists('ledger_entries'); Schema::dropIfExists('wallets'); Schema::dropIfExists('tournaments'); Schema::dropIfExists('personal_access_tokens'); Schema::dropIfExists('sessions'); Schema::dropIfExists('password_reset_tokens'); Schema::dropIfExists('users'); Schema::dropIfExists('cache'); Schema::dropIfExists('cache_locks'); Schema::dropIfExists('jobs'); Schema::dropIfExists('job_batches'); Schema::dropIfExists('failed_jobs');
    }
};
