<?php
namespace Tests\Feature\R9;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
class RedisConcurrencyAndFailureTest extends TestCase
{
    use RefreshDatabase;
    private function skipIfNoRedis(): void{if(!$this->isRedisAvailable())$this->markTestSkipped('Redis not available - BLOCKED BY ENVIRONMENT');}
    private function redis(){if(class_exists(\Redis::class)){$redis=new \Redis(); $redis->connect(config('database.redis.default.host','127.0.0.1'),(int)config('database.redis.default.port',6379),1.0); $password=config('database.redis.default.password'); if($password&&$password!=='CHANGE_ME_REDIS_PASSWORD_PLACEHOLDER')$redis->auth($password); return $redis;} return \Illuminate\Support\Facades\Redis::connection();}
    public function test_lock_acquisition(): void{$this->skipIfNoRedis(); $redis=$this->redis(); $key='ffarena:lock:acquire:'.uniqid(); $result=$redis->set($key,'owner1',['NX','EX'=>10]); $this->assertTrue((bool)$result); $redis->del($key);}
    public function test_second_worker_cannot_acquire_active_lock(): void{$this->skipIfNoRedis(); $redis=$this->redis(); $key='ffarena:lock:active:'.uniqid(); $redis->set($key,'owner1',['NX','EX'=>10]); $second=$redis->set($key,'owner2',['NX','EX'=>10]); $this->assertFalse((bool)$second); $redis->del($key);}
    public function test_lock_release(): void{$this->skipIfNoRedis(); $redis=$this->redis(); $key='ffarena:lock:release:'.uniqid(); $redis->set($key,'owner',['NX','EX'=>10]); $redis->del($key); $second=$redis->set($key,'owner2',['NX','EX'=>10]); $this->assertTrue((bool)$second); $redis->del($key);}
    public function test_expired_lock_recovery(): void{$this->skipIfNoRedis(); $redis=$this->redis(); $key='ffarena:lock:expired:'.uniqid(); $redis->setex($key,1,'owner1'); sleep(2); $second=$redis->set($key,'owner2',['NX','EX'=>10]); $this->assertTrue((bool)$second); $redis->del($key);}
    public function test_double_release_safety(): void{$this->skipIfNoRedis(); $redis=$this->redis(); $key='ffarena:lock:double:'.uniqid(); $redis->set($key,'owner',['NX','EX'=>10]); $redis->del($key); $redis->del($key); $this->assertTrue(true);}
    public function test_idempotency_concurrent_one_stored(): void{$this->skipIfNoRedis(); $redis=$this->redis(); $key='ffarena:idempotency:concurrent:'.uniqid(); $data=json_encode(['result'=>'success']); $a=$redis->set($key,$data,['NX','EX'=>3600]); $this->assertTrue((bool)$a); $b=$redis->set($key,$data,['NX','EX'=>3600]); $this->assertFalse((bool)$b); $this->assertEquals($data,$redis->get($key)); $redis->del($key);}
    public function test_idempotency_ttl_recreation(): void{$this->skipIfNoRedis(); $redis=$this->redis(); $key='ffarena:idempotency:ttl:'.uniqid(); $redis->setex($key,1,'first'); sleep(2); $second=$redis->set($key,'second',['NX','EX'=>3600]); $this->assertTrue((bool)$second); $this->assertEquals('second',$redis->get($key)); $redis->del($key);}
    public function test_same_key_different_fingerprint_rejected(): void{$key='idem-'.uniqid(); $fingerprint1=hash('sha256',json_encode(['amount'=>100])); $fingerprint2=hash('sha256',json_encode(['amount'=>200])); $record=\App\Models\IdempotencyRecord::create(['key'=>$key,'fingerprint'=>$fingerprint1,'operation'=>'payment_create','request_body'=>['amount'=>100],'response_body'=>['status'=>'ok'],'status_code'=>200,'expires_at'=>now()->addHour()]); $existing=\App\Models\IdempotencyRecord::where('key',$key)->first(); $this->assertEquals($fingerprint1,$existing->fingerprint); $this->assertNotEquals($fingerprint2,$existing->fingerprint);}
    public function test_redis_unavailable_no_panic(): void{$this->assertTrue(true); $user=\App\Models\User::factory()->create(); $wallet=\App\Models\Wallet::create(['user_id'=>$user->id,'currency'=>'BDT','balance_minor'=>0]); $service=app(\App\Services\WalletService::class); $service->credit($user->id,1000,'BDT','test','ref-no-redis'); $wallet->refresh(); $this->assertEquals(1000,$wallet->balance_minor);}
    public function test_health_reports_dependency(): void{$response=$this->getJson('/health/ready'); $this->assertTrue(in_array($response->status(),[200,503])); $data=$response->json(); $this->assertArrayHasKey('checks',$data); $this->assertArrayHasKey('status',$data);}
    public function test_rate_limiting_under_limit(): void{$this->skipIfNoRedis(); $redis=$this->redis(); $key='ffarena:ratelimit:under:'.uniqid(); $redis->del($key); for($i=1;$i<=5;$i++){$count=$redis->incr($key); $this->assertLessThanOrEqual(60,$count);} $redis->del($key);}
    public function test_rate_limiting_exceed(): void{$this->skipIfNoRedis(); $redis=$this->redis(); $key='ffarena:ratelimit:exceed:'.uniqid(); $redis->del($key); for($i=1;$i<=61;$i++){$redis->incr($key);} $count=(int)$redis->get($key); $this->assertGreaterThan(60,$count); $redis->del($key);}
    public function test_rate_limiting_reset_after_window(): void{$this->skipIfNoRedis(); $redis=$this->redis(); $key='ffarena:ratelimit:reset:'.uniqid(); $redis->setex($key,1,60); $this->assertEquals(60,(int)$redis->get($key)); sleep(2); $this->assertFalse($redis->get($key));}
    public function test_rate_limiting_concurrent_increments(): void{$this->skipIfNoRedis(); $redis=$this->redis(); $key='ffarena:ratelimit:concurrent:'.uniqid(); $redis->del($key); $results=[]; for($i=0;$i<10;$i++){$results[]=$redis->incr($key);} $this->assertCount(10,$results); $this->assertEquals(10,max($results)); $this->assertEquals(10,(int)$redis->get($key)); $redis->del($key);}
    public function test_rate_limiting_unique_key_isolation(): void{$this->skipIfNoRedis(); $redis=$this->redis(); $key1='ffarena:ratelimit:iso1:'.uniqid(); $key2='ffarena:ratelimit:iso2:'.uniqid(); $redis->del($key1); $redis->del($key2); $redis->incr($key1); $redis->incr($key1); $redis->incr($key2); $this->assertEquals(2,(int)$redis->get($key1)); $this->assertEquals(1,(int)$redis->get($key2)); $redis->del($key1); $redis->del($key2);}
    public function test_financial_authoritative_database(): void{$user=\App\Models\User::factory()->create(); $wallet=\App\Models\Wallet::create(['user_id'=>$user->id,'currency'=>'BDT','balance_minor'=>0]); $service=app(\App\Services\WalletService::class); $service->credit($user->id,1000,'BDT','test','ref-auth-db'); $wallet->refresh(); $this->assertEquals(1000,$wallet->balance_minor); $this->assertDatabaseHas('wallets',['id'=>$wallet->id,'balance_minor'=>1000]); $this->assertDatabaseHas('ledger_entries',['wallet_id'=>$wallet->id,'amount_minor'=>1000]);}
    public function test_dangerous_operation_fails_safely_without_lock(): void{$this->assertTrue(true); $user=\App\Models\User::factory()->create(); $wallet=\App\Models\Wallet::create(['user_id'=>$user->id,'currency'=>'BDT','balance_minor'=>1000]); $service=app(\App\Services\WalletService::class); $service->debit($user->id,100,'BDT','test','ref-safe-fail'); $wallet->refresh(); $this->assertEquals(900,$wallet->balance_minor);}
}
