package storage
import ("context"; "database/sql"; "fmt"; "time"; "github.com/ffarena/payment-gateway-go/internal/domain"; "github.com/ffarena/payment-gateway-go/internal/models")
type PostgresStore struct{db *sql.DB}
func NewPostgresStore(db *sql.DB) *PostgresStore {return &PostgresStore{db:db}}
func (s *PostgresStore) Migrate(ctx context.Context) error {
    queries:=[]string{
        `CREATE TABLE IF NOT EXISTS payments (id TEXT PRIMARY KEY, user_id BIGINT NOT NULL, wallet_id BIGINT, provider TEXT NOT NULL, external_id TEXT UNIQUE NOT NULL, provider_reference TEXT UNIQUE, amount_minor BIGINT NOT NULL, currency TEXT NOT NULL, status TEXT NOT NULL, idempotency_key TEXT UNIQUE NOT NULL, idempotency_fingerprint TEXT, metadata JSONB, authorized_at TIMESTAMPTZ, succeeded_at TIMESTAMPTZ, failed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL)`,
        `CREATE INDEX IF NOT EXISTS idx_payments_user_id ON payments(user_id)`,
        `CREATE INDEX IF NOT EXISTS idx_payments_external_id ON payments(external_id)`,
        `CREATE INDEX IF NOT EXISTS idx_payments_idempotency_key ON payments(idempotency_key)`,
        `CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status)`,
        `CREATE INDEX IF NOT EXISTS idx_payments_provider ON payments(provider)`,
        `CREATE INDEX IF NOT EXISTS idx_payments_created_at ON payments(created_at)`,
        `CREATE TABLE IF NOT EXISTS wallets (id BIGSERIAL PRIMARY KEY, user_id BIGINT NOT NULL, currency TEXT NOT NULL, balance_minor BIGINT NOT NULL DEFAULT 0, is_locked BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, UNIQUE(user_id, currency))`,
        `CREATE INDEX IF NOT EXISTS idx_wallets_user_id ON wallets(user_id)`,
        `CREATE TABLE IF NOT EXISTS ledger_entries (id BIGSERIAL PRIMARY KEY, wallet_id BIGINT NOT NULL REFERENCES wallets(id), user_id BIGINT NOT NULL, direction TEXT NOT NULL, amount_minor BIGINT NOT NULL, balance_after_minor BIGINT NOT NULL, reference_type TEXT, reference_id TEXT, idempotency_key TEXT UNIQUE, metadata JSONB, created_at TIMESTAMPTZ NOT NULL)`,
        `CREATE INDEX IF NOT EXISTS idx_ledger_wallet_id ON ledger_entries(wallet_id)`,
        `CREATE INDEX IF NOT EXISTS idx_ledger_created_at ON ledger_entries(created_at)`,
        `CREATE INDEX IF NOT EXISTS idx_ledger_reference ON ledger_entries(reference_id)`,
        `CREATE TABLE IF NOT EXISTS payouts (id TEXT PRIMARY KEY, user_id BIGINT NOT NULL, tournament_id BIGINT, amount_minor BIGINT NOT NULL, currency TEXT NOT NULL, status TEXT NOT NULL, external_id TEXT UNIQUE NOT NULL, provider TEXT NOT NULL, idempotency_key TEXT UNIQUE NOT NULL, metadata JSONB, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL)`,
        `CREATE INDEX IF NOT EXISTS idx_payouts_user_id ON payouts(user_id)`,
        `CREATE INDEX IF NOT EXISTS idx_payouts_external_id ON payouts(external_id)`,
        `CREATE INDEX IF NOT EXISTS idx_payouts_idempotency_key ON payouts(idempotency_key)`,
        `CREATE TABLE IF NOT EXISTS idempotency_records (key TEXT PRIMARY KEY, fingerprint TEXT NOT NULL, operation TEXT NOT NULL, user_id BIGINT, request_body JSONB, response_body JSONB, status_code INT, expires_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL)`,
        `CREATE INDEX IF NOT EXISTS idx_idempotency_expires_at ON idempotency_records(expires_at)`,
        `CREATE INDEX IF NOT EXISTS idx_idempotency_operation ON idempotency_records(operation)`,
        `CREATE TABLE IF NOT EXISTS webhook_events (id TEXT PRIMARY KEY, provider TEXT NOT NULL, event_type TEXT, event_id TEXT UNIQUE NOT NULL, payload JSONB, signature TEXT, state TEXT NOT NULL, attempts INT NOT NULL DEFAULT 0, last_error TEXT, processed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL)`,
        `CREATE INDEX IF NOT EXISTS idx_webhook_event_id ON webhook_events(event_id)`,
        `CREATE INDEX IF NOT EXISTS idx_webhook_provider ON webhook_events(provider)`,
        `CREATE INDEX IF NOT EXISTS idx_webhook_state ON webhook_events(state)`,
        `CREATE TABLE IF NOT EXISTS financial_settlements (id TEXT PRIMARY KEY, tournament_id BIGINT NOT NULL, total_amount_minor BIGINT NOT NULL, currency TEXT NOT NULL, status TEXT NOT NULL, idempotency_key TEXT UNIQUE NOT NULL, metadata JSONB, completed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL)`,
        `CREATE INDEX IF NOT EXISTS idx_settlements_tournament_id ON financial_settlements(tournament_id)`,
        `CREATE INDEX IF NOT EXISTS idx_settlements_idempotency_key ON financial_settlements(idempotency_key)`,
    }
    for _,q:=range queries{if _,err:=s.db.ExecContext(ctx,q); err!=nil{return fmt.Errorf("migrate failed: %w, query: %s",err,q)}}
    return nil
}
func (s *PostgresStore) CreatePayment(ctx context.Context, payment *models.Payment) error{query:=`INSERT INTO payments (id, user_id, wallet_id, provider, external_id, amount_minor, currency, status, idempotency_key, created_at, updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`; _,err:=s.db.ExecContext(ctx,query,payment.ID,payment.UserID,payment.WalletID,payment.Provider,payment.ExternalID,payment.AmountMinor,payment.Currency,payment.Status,payment.IdempotencyKey,time.Now().UTC(),time.Now().UTC()); return err}
func (s *PostgresStore) GetPaymentByID(ctx context.Context, id string) (*models.Payment, error){var p models.Payment; err:=s.db.QueryRowContext(ctx,`SELECT id, user_id, provider, external_id, amount_minor, currency, status, idempotency_key FROM payments WHERE id=$1`,id).Scan(&p.ID,&p.UserID,&p.Provider,&p.ExternalID,&p.AmountMinor,&p.Currency,&p.Status,&p.IdempotencyKey); if err!=nil{return nil, err}; return &p, nil}
func (s *PostgresStore) GetPaymentByExternalID(ctx context.Context, externalID string) (*models.Payment, error){var p models.Payment; err:=s.db.QueryRowContext(ctx,`SELECT id, user_id, provider, external_id, amount_minor, currency, status, idempotency_key FROM payments WHERE external_id=$1`,externalID).Scan(&p.ID,&p.UserID,&p.Provider,&p.ExternalID,&p.AmountMinor,&p.Currency,&p.Status,&p.IdempotencyKey); if err!=nil{return nil, err}; return &p, nil}
func (s *PostgresStore) GetPaymentByIdempotencyKey(ctx context.Context, key string) (*models.Payment, error){var p models.Payment; err:=s.db.QueryRowContext(ctx,`SELECT id, user_id, provider, external_id, amount_minor, currency, status, idempotency_key FROM payments WHERE idempotency_key=$1`,key).Scan(&p.ID,&p.UserID,&p.Provider,&p.ExternalID,&p.AmountMinor,&p.Currency,&p.Status,&p.IdempotencyKey); if err!=nil{return nil, err}; return &p, nil}
func (s *PostgresStore) UpdatePayment(ctx context.Context, payment *models.Payment) error{_,err:=s.db.ExecContext(ctx,`UPDATE payments SET status=$1, updated_at=$2 WHERE id=$3`,payment.Status,time.Now().UTC(),payment.ID); return err}
func (s *PostgresStore) ListPaymentsByUser(ctx context.Context, userID int64) ([]*models.Payment, error){rows,err:=s.db.QueryContext(ctx,`SELECT id, user_id, provider, external_id, amount_minor, currency, status, idempotency_key FROM payments WHERE user_id=$1`,userID); if err!=nil{return nil, err}; defer rows.Close(); var result []*models.Payment; for rows.Next(){var p models.Payment; if err:=rows.Scan(&p.ID,&p.UserID,&p.Provider,&p.ExternalID,&p.AmountMinor,&p.Currency,&p.Status,&p.IdempotencyKey); err!=nil{return nil, err}; result=append(result,&p)}; return result, nil}
func (s *PostgresStore) GetWalletByUserAndCurrency(ctx context.Context, userID int64, currency string) (*models.Wallet, error){var w models.Wallet; err:=s.db.QueryRowContext(ctx,`SELECT id, user_id, currency, balance_minor FROM wallets WHERE user_id=$1 AND currency=$2`,userID,currency).Scan(&w.ID,&w.UserID,&w.Currency,&w.BalanceMinor); if err!=nil{return nil, err}; return &w, nil}
func (s *PostgresStore) CreateWallet(ctx context.Context, wallet *models.Wallet) error{return s.db.QueryRowContext(ctx,`INSERT INTO wallets (user_id, currency, balance_minor, created_at, updated_at) VALUES ($1,$2,$3,$4,$5) RETURNING id`,wallet.UserID,wallet.Currency,wallet.BalanceMinor,time.Now().UTC(),time.Now().UTC()).Scan(&wallet.ID)}
func (s *PostgresStore) UpdateWalletBalance(ctx context.Context, walletID int64, balanceMinor int64) error{_,err:=s.db.ExecContext(ctx,`UPDATE wallets SET balance_minor=$1, updated_at=$2 WHERE id=$3`,balanceMinor,time.Now().UTC(),walletID); return err}
func (s *PostgresStore) LockWalletForUpdate(ctx context.Context, walletID int64) (*models.Wallet, error){var w models.Wallet; err:=s.db.QueryRowContext(ctx,`SELECT id, user_id, currency, balance_minor FROM wallets WHERE id=$1 FOR UPDATE`,walletID).Scan(&w.ID,&w.UserID,&w.Currency,&w.BalanceMinor); if err!=nil{return nil, err}; return &w, nil}
func (s *PostgresStore) CreateLedgerEntry(ctx context.Context, entry *models.LedgerEntry) error{_,err:=s.db.ExecContext(ctx,`INSERT INTO ledger_entries (wallet_id, user_id, direction, amount_minor, balance_after_minor, reference_type, reference_id, idempotency_key, created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)`,entry.WalletID,entry.UserID,entry.Direction,entry.AmountMinor,entry.BalanceAfterMinor,entry.ReferenceType,entry.ReferenceID,entry.IdempotencyKey,time.Now().UTC()); return err}
func (s *PostgresStore) ListLedgerByWallet(ctx context.Context, walletID int64) ([]*models.LedgerEntry, error){rows,err:=s.db.QueryContext(ctx,`SELECT id, wallet_id, user_id, direction, amount_minor, balance_after_minor FROM ledger_entries WHERE wallet_id=$1 ORDER BY created_at`,walletID); if err!=nil{return nil, err}; defer rows.Close(); var result []*models.LedgerEntry; for rows.Next(){var e models.LedgerEntry; if err:=rows.Scan(&e.ID,&e.WalletID,&e.UserID,&e.Direction,&e.AmountMinor,&e.BalanceAfterMinor); err!=nil{return nil, err}; result=append(result,&e)}; return result, nil}
func (s *PostgresStore) CalculateLedgerBalance(ctx context.Context, walletID int64) (int64, error){var credits,debits sql.NullInt64; err:=s.db.QueryRowContext(ctx,`SELECT COALESCE(SUM(CASE WHEN direction='credit' THEN amount_minor ELSE 0 END),0), COALESCE(SUM(CASE WHEN direction='debit' THEN amount_minor ELSE 0 END),0) FROM ledger_entries WHERE wallet_id=$1`,walletID).Scan(&credits,&debits); if err!=nil{return 0, err}; return credits.Int64-debits.Int64, nil}
func (s *PostgresStore) VerifyLedgerIntegrity(ctx context.Context, walletID int64) (bool, error){rows,err:=s.db.QueryContext(ctx,`SELECT direction, amount_minor, balance_after_minor FROM ledger_entries WHERE wallet_id=$1 ORDER BY created_at, id`,walletID); if err!=nil{return false, err}; defer rows.Close(); var running int64; for rows.Next(){var dir string; var amount,balanceAfter int64; if err:=rows.Scan(&dir,&amount,&balanceAfter); err!=nil{return false, err}; if dir=="credit"{running+=amount} else {running-=amount}; if running!=balanceAfter{return false, nil}}; var stored int64; err=s.db.QueryRowContext(ctx,`SELECT balance_minor FROM wallets WHERE id=$1`,walletID).Scan(&stored); if err!=nil{return false, err}; return running==stored, nil}
func (s *PostgresStore) CreatePayout(ctx context.Context, payout *models.Payout) error{_,err:=s.db.ExecContext(ctx,`INSERT INTO payouts (id, user_id, amount_minor, currency, status, external_id, provider, idempotency_key, created_at, updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,payout.ID,payout.UserID,payout.AmountMinor,payout.Currency,payout.Status,payout.ExternalID,payout.Provider,payout.IdempotencyKey,time.Now().UTC(),time.Now().UTC()); return err}
func (s *PostgresStore) GetPayoutByID(ctx context.Context, id string) (*models.Payout, error){var p models.Payout; err:=s.db.QueryRowContext(ctx,`SELECT id, user_id, amount_minor, currency, status, external_id, provider, idempotency_key FROM payouts WHERE id=$1`,id).Scan(&p.ID,&p.UserID,&p.AmountMinor,&p.Currency,&p.Status,&p.ExternalID,&p.Provider,&p.IdempotencyKey); if err!=nil{return nil, err}; return &p, nil}
func (s *PostgresStore) GetPayoutByExternalID(ctx context.Context, externalID string) (*models.Payout, error){var p models.Payout; err:=s.db.QueryRowContext(ctx,`SELECT id, user_id, amount_minor, currency, status, external_id, provider, idempotency_key FROM payouts WHERE external_id=$1`,externalID).Scan(&p.ID,&p.UserID,&p.AmountMinor,&p.Currency,&p.Status,&p.ExternalID,&p.Provider,&p.IdempotencyKey); if err!=nil{return nil, err}; return &p, nil}
func (s *PostgresStore) GetPayoutByIdempotencyKey(ctx context.Context, key string) (*models.Payout, error){var p models.Payout; err:=s.db.QueryRowContext(ctx,`SELECT id, user_id, amount_minor, currency, status, external_id, provider, idempotency_key FROM payouts WHERE idempotency_key=$1`,key).Scan(&p.ID,&p.UserID,&p.AmountMinor,&p.Currency,&p.Status,&p.ExternalID,&p.Provider,&p.IdempotencyKey); if err!=nil{return nil, err}; return &p, nil}
func (s *PostgresStore) UpdatePayout(ctx context.Context, payout *models.Payout) error{_,err:=s.db.ExecContext(ctx,`UPDATE payouts SET status=$1, updated_at=$2 WHERE id=$3`,payout.Status,time.Now().UTC(),payout.ID); return err}
func (s *PostgresStore) GetIdempotency(ctx context.Context, key string) (*domain.IdempotencyRecord, error){var r domain.IdempotencyRecord; err:=s.db.QueryRowContext(ctx,`SELECT key, fingerprint, operation, expires_at FROM idempotency_records WHERE key=$1`,key).Scan(&r.Key,&r.Fingerprint,&r.Operation,&r.ExpiresAt); if err!=nil{return nil, err}; return &r, nil}
func (s *PostgresStore) SetIdempotency(ctx context.Context, record *domain.IdempotencyRecord) error{_,err:=s.db.ExecContext(ctx,`INSERT INTO idempotency_records (key, fingerprint, operation, expires_at, created_at, updated_at) VALUES ($1,$2,$3,$4,$5,$6) ON CONFLICT (key) DO UPDATE SET fingerprint=$2, operation=$3, expires_at=$4, updated_at=$6`,record.Key,record.Fingerprint,record.Operation,record.ExpiresAt,time.Now().UTC(),time.Now().UTC()); return err}
func (s *PostgresStore) DeleteIdempotency(ctx context.Context, key string) error{_,err:=s.db.ExecContext(ctx,`DELETE FROM idempotency_records WHERE key=$1`,key); return err}
func (s *PostgresStore) CleanupIdempotency(ctx context.Context) error{_,err:=s.db.ExecContext(ctx,`DELETE FROM idempotency_records WHERE expires_at<$1`,time.Now().UTC()); return err}
func (s *PostgresStore) HealthCheck(ctx context.Context) error{return s.db.PingContext(ctx)}
func (s *PostgresStore) Close() error{return s.db.Close()}
