package storage
import ("context"; "database/sql"; "fmt"; "time"; "github.com/ffarena/payment-gateway-go/internal/domain"; "github.com/ffarena/payment-gateway-go/internal/models")
type SQLiteStore struct{db *sql.DB}
func NewSQLiteStore(db *sql.DB) *SQLiteStore {return &SQLiteStore{db:db}}
func (s *SQLiteStore) Migrate(ctx context.Context) error{
    queries:=[]string{
        `CREATE TABLE IF NOT EXISTS payments (id TEXT PRIMARY KEY, user_id INTEGER NOT NULL, wallet_id INTEGER, provider TEXT NOT NULL, external_id TEXT UNIQUE NOT NULL, amount_minor INTEGER NOT NULL, currency TEXT NOT NULL, status TEXT NOT NULL, idempotency_key TEXT UNIQUE NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL)`,
        `CREATE TABLE IF NOT EXISTS wallets (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, currency TEXT NOT NULL, balance_minor INTEGER NOT NULL DEFAULT 0, is_locked BOOLEAN NOT NULL DEFAULT 0, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE(user_id, currency))`,
        `CREATE TABLE IF NOT EXISTS ledger_entries (id INTEGER PRIMARY KEY AUTOINCREMENT, wallet_id INTEGER NOT NULL, user_id INTEGER NOT NULL, direction TEXT NOT NULL, amount_minor INTEGER NOT NULL, balance_after_minor INTEGER NOT NULL, reference_type TEXT, reference_id TEXT, idempotency_key TEXT UNIQUE, created_at DATETIME NOT NULL)`,
        `CREATE TABLE IF NOT EXISTS payouts (id TEXT PRIMARY KEY, user_id INTEGER NOT NULL, amount_minor INTEGER NOT NULL, currency TEXT NOT NULL, status TEXT NOT NULL, external_id TEXT UNIQUE NOT NULL, provider TEXT NOT NULL, idempotency_key TEXT UNIQUE NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL)`,
        `CREATE TABLE IF NOT EXISTS idempotency_records (key TEXT PRIMARY KEY, fingerprint TEXT NOT NULL, operation TEXT NOT NULL, expires_at DATETIME, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL)`,
    }
    for _,q:=range queries{if _,err:=s.db.ExecContext(ctx,q); err!=nil{return fmt.Errorf("migrate failed: %w",err)}}
    return nil
}
func (s *SQLiteStore) CreatePayment(ctx context.Context, payment *models.Payment) error{_,err:=s.db.ExecContext(ctx,`INSERT INTO payments (id, user_id, provider, external_id, amount_minor, currency, status, idempotency_key, created_at, updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)`,payment.ID,payment.UserID,payment.Provider,payment.ExternalID,payment.AmountMinor,payment.Currency,payment.Status,payment.IdempotencyKey,time.Now().UTC(),time.Now().UTC()); return err}
func (s *SQLiteStore) GetPaymentByID(ctx context.Context, id string) (*models.Payment, error){var p models.Payment; err:=s.db.QueryRowContext(ctx,`SELECT id, user_id, provider, external_id, amount_minor, currency, status, idempotency_key FROM payments WHERE id=?`,id).Scan(&p.ID,&p.UserID,&p.Provider,&p.ExternalID,&p.AmountMinor,&p.Currency,&p.Status,&p.IdempotencyKey); if err!=nil{return nil, err}; return &p, nil}
func (s *SQLiteStore) GetPaymentByExternalID(ctx context.Context, externalID string) (*models.Payment, error){var p models.Payment; err:=s.db.QueryRowContext(ctx,`SELECT id, user_id, provider, external_id, amount_minor, currency, status, idempotency_key FROM payments WHERE external_id=?`,externalID).Scan(&p.ID,&p.UserID,&p.Provider,&p.ExternalID,&p.AmountMinor,&p.Currency,&p.Status,&p.IdempotencyKey); if err!=nil{return nil, err}; return &p, nil}
func (s *SQLiteStore) GetPaymentByIdempotencyKey(ctx context.Context, key string) (*models.Payment, error){var p models.Payment; err:=s.db.QueryRowContext(ctx,`SELECT id, user_id, provider, external_id, amount_minor, currency, status, idempotency_key FROM payments WHERE idempotency_key=?`,key).Scan(&p.ID,&p.UserID,&p.Provider,&p.ExternalID,&p.AmountMinor,&p.Currency,&p.Status,&p.IdempotencyKey); if err!=nil{return nil, err}; return &p, nil}
func (s *SQLiteStore) UpdatePayment(ctx context.Context, payment *models.Payment) error{_,err:=s.db.ExecContext(ctx,`UPDATE payments SET status=?, updated_at=? WHERE id=?`,payment.Status,time.Now().UTC(),payment.ID); return err}
func (s *SQLiteStore) ListPaymentsByUser(ctx context.Context, userID int64) ([]*models.Payment, error){rows,err:=s.db.QueryContext(ctx,`SELECT id, user_id, provider, external_id, amount_minor, currency, status, idempotency_key FROM payments WHERE user_id=?`,userID); if err!=nil{return nil, err}; defer rows.Close(); var result []*models.Payment; for rows.Next(){var p models.Payment; if err:=rows.Scan(&p.ID,&p.UserID,&p.Provider,&p.ExternalID,&p.AmountMinor,&p.Currency,&p.Status,&p.IdempotencyKey); err!=nil{return nil, err}; result=append(result,&p)}; return result, nil}
func (s *SQLiteStore) GetWalletByUserAndCurrency(ctx context.Context, userID int64, currency string) (*models.Wallet, error){var w models.Wallet; err:=s.db.QueryRowContext(ctx,`SELECT id, user_id, currency, balance_minor FROM wallets WHERE user_id=? AND currency=?`,userID,currency).Scan(&w.ID,&w.UserID,&w.Currency,&w.BalanceMinor); if err!=nil{return nil, err}; return &w, nil}
func (s *SQLiteStore) CreateWallet(ctx context.Context, wallet *models.Wallet) error{return s.db.QueryRowContext(ctx,`INSERT INTO wallets (user_id, currency, balance_minor, created_at, updated_at) VALUES (?,?,?,?,?) RETURNING id`,wallet.UserID,wallet.Currency,wallet.BalanceMinor,time.Now().UTC(),time.Now().UTC()).Scan(&wallet.ID)}
func (s *SQLiteStore) UpdateWalletBalance(ctx context.Context, walletID int64, balanceMinor int64) error{_,err:=s.db.ExecContext(ctx,`UPDATE wallets SET balance_minor=?, updated_at=? WHERE id=?`,balanceMinor,time.Now().UTC(),walletID); return err}
func (s *SQLiteStore) LockWalletForUpdate(ctx context.Context, walletID int64) (*models.Wallet, error){var w models.Wallet; err:=s.db.QueryRowContext(ctx,`SELECT id, user_id, currency, balance_minor FROM wallets WHERE id=?`,walletID).Scan(&w.ID,&w.UserID,&w.Currency,&w.BalanceMinor); if err!=nil{return nil, err}; return &w, nil}
func (s *SQLiteStore) CreateLedgerEntry(ctx context.Context, entry *models.LedgerEntry) error{_,err:=s.db.ExecContext(ctx,`INSERT INTO ledger_entries (wallet_id, user_id, direction, amount_minor, balance_after_minor, reference_type, reference_id, idempotency_key, created_at) VALUES (?,?,?,?,?,?,?,?,?)`,entry.WalletID,entry.UserID,entry.Direction,entry.AmountMinor,entry.BalanceAfterMinor,entry.ReferenceType,entry.ReferenceID,entry.IdempotencyKey,time.Now().UTC()); return err}
func (s *SQLiteStore) ListLedgerByWallet(ctx context.Context, walletID int64) ([]*models.LedgerEntry, error){rows,err:=s.db.QueryContext(ctx,`SELECT id, wallet_id, user_id, direction, amount_minor, balance_after_minor FROM ledger_entries WHERE wallet_id=? ORDER BY created_at`,walletID); if err!=nil{return nil, err}; defer rows.Close(); var result []*models.LedgerEntry; for rows.Next(){var e models.LedgerEntry; if err:=rows.Scan(&e.ID,&e.WalletID,&e.UserID,&e.Direction,&e.AmountMinor,&e.BalanceAfterMinor); err!=nil{return nil, err}; result=append(result,&e)}; return result, nil}
func (s *SQLiteStore) CalculateLedgerBalance(ctx context.Context, walletID int64) (int64, error){var credits,debits sql.NullInt64; err:=s.db.QueryRowContext(ctx,`SELECT COALESCE(SUM(CASE WHEN direction='credit' THEN amount_minor ELSE 0 END),0), COALESCE(SUM(CASE WHEN direction='debit' THEN amount_minor ELSE 0 END),0) FROM ledger_entries WHERE wallet_id=?`,walletID).Scan(&credits,&debits); if err!=nil{return 0, err}; return credits.Int64-debits.Int64, nil}
func (s *SQLiteStore) VerifyLedgerIntegrity(ctx context.Context, walletID int64) (bool, error){rows,err:=s.db.QueryContext(ctx,`SELECT direction, amount_minor, balance_after_minor FROM ledger_entries WHERE wallet_id=? ORDER BY created_at, id`,walletID); if err!=nil{return false, err}; defer rows.Close(); var running int64; for rows.Next(){var dir string; var amount,balanceAfter int64; if err:=rows.Scan(&dir,&amount,&balanceAfter); err!=nil{return false, err}; if dir=="credit"{running+=amount} else {running-=amount}; if running!=balanceAfter{return false, nil}}; var stored int64; err=s.db.QueryRowContext(ctx,`SELECT balance_minor FROM wallets WHERE id=?`,walletID).Scan(&stored); if err!=nil{return false, err}; return running==stored, nil}
func (s *SQLiteStore) CreatePayout(ctx context.Context, payout *models.Payout) error{_,err:=s.db.ExecContext(ctx,`INSERT INTO payouts (id, user_id, amount_minor, currency, status, external_id, provider, idempotency_key, created_at, updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)`,payout.ID,payout.UserID,payout.AmountMinor,payout.Currency,payout.Status,payout.ExternalID,payout.Provider,payout.IdempotencyKey,time.Now().UTC(),time.Now().UTC()); return err}
func (s *SQLiteStore) GetPayoutByID(ctx context.Context, id string) (*models.Payout, error){var p models.Payout; err:=s.db.QueryRowContext(ctx,`SELECT id, user_id, amount_minor, currency, status, external_id, provider, idempotency_key FROM payouts WHERE id=?`,id).Scan(&p.ID,&p.UserID,&p.AmountMinor,&p.Currency,&p.Status,&p.ExternalID,&p.Provider,&p.IdempotencyKey); if err!=nil{return nil, err}; return &p, nil}
func (s *SQLiteStore) GetPayoutByExternalID(ctx context.Context, externalID string) (*models.Payout, error){var p models.Payout; err:=s.db.QueryRowContext(ctx,`SELECT id, user_id, amount_minor, currency, status, external_id, provider, idempotency_key FROM payouts WHERE external_id=?`,externalID).Scan(&p.ID,&p.UserID,&p.AmountMinor,&p.Currency,&p.Status,&p.ExternalID,&p.Provider,&p.IdempotencyKey); if err!=nil{return nil, err}; return &p, nil}
func (s *SQLiteStore) GetPayoutByIdempotencyKey(ctx context.Context, key string) (*models.Payout, error){var p models.Payout; err:=s.db.QueryRowContext(ctx,`SELECT id, user_id, amount_minor, currency, status, external_id, provider, idempotency_key FROM payouts WHERE idempotency_key=?`,key).Scan(&p.ID,&p.UserID,&p.AmountMinor,&p.Currency,&p.Status,&p.ExternalID,&p.Provider,&p.IdempotencyKey); if err!=nil{return nil, err}; return &p, nil}
func (s *SQLiteStore) UpdatePayout(ctx context.Context, payout *models.Payout) error{_,err:=s.db.ExecContext(ctx,`UPDATE payouts SET status=?, updated_at=? WHERE id=?`,payout.Status,time.Now().UTC(),payout.ID); return err}
func (s *SQLiteStore) GetIdempotency(ctx context.Context, key string) (*domain.IdempotencyRecord, error){var r domain.IdempotencyRecord; err:=s.db.QueryRowContext(ctx,`SELECT key, fingerprint, operation, expires_at FROM idempotency_records WHERE key=?`,key).Scan(&r.Key,&r.Fingerprint,&r.Operation,&r.ExpiresAt); if err!=nil{return nil, err}; return &r, nil}
func (s *SQLiteStore) SetIdempotency(ctx context.Context, record *domain.IdempotencyRecord) error{_,err:=s.db.ExecContext(ctx,`INSERT OR REPLACE INTO idempotency_records (key, fingerprint, operation, expires_at, created_at, updated_at) VALUES (?,?,?,?,?,?)`,record.Key,record.Fingerprint,record.Operation,record.ExpiresAt,time.Now().UTC(),time.Now().UTC()); return err}
func (s *SQLiteStore) DeleteIdempotency(ctx context.Context, key string) error{_,err:=s.db.ExecContext(ctx,`DELETE FROM idempotency_records WHERE key=?`,key); return err}
func (s *SQLiteStore) CleanupIdempotency(ctx context.Context) error{_,err:=s.db.ExecContext(ctx,`DELETE FROM idempotency_records WHERE expires_at<?`,time.Now().UTC()); return err}
func (s *SQLiteStore) HealthCheck(ctx context.Context) error{return s.db.PingContext(ctx)}
func (s *SQLiteStore) Close() error{return s.db.Close()}
