<?php

/**
 * G3 — benchmark report generator.
 *
 *   php scripts/perf/generate-report.php [output.md]
 *
 * Reads every storage/perf/*.json produced by the benchmark scripts and
 * renders:
 *   * a Markdown report (default: storage/perf/REPORT.md) with p50/p90/p95/
 *     p99, throughput, error rates and the query plans, and
 *   * a machine-readable storage/perf/summary.json for CI comparisons.
 *
 * It never invents data: if no JSON results exist it reports exactly that and
 * exits non-zero so CI cannot pass on an empty report.
 */

declare(strict_types=1);

$root = dirname(__DIR__, 2);
$perfDir = $root.'/storage/perf';
$outputPath = $argv[1] ?? $perfDir.'/REPORT.md';

if (! is_dir($perfDir)) {
    fwrite(STDERR, "ERROR: no storage/perf directory — run a benchmark first.\n");
    exit(1);
}

$files = glob($perfDir.'/*.json');

$results = [];

foreach ($files as $file) {
    $data = json_decode((string) file_get_contents($file), true);

    if (is_array($data) && isset($data['name'])) {
        $results[$data['name']] = $data;
    }
}

ksort($results);

if ($results === []) {
    fwrite(STDERR, "ERROR: no benchmark results found in {$perfDir}.\n");
    exit(1);
}

$lines = [];
$lines[] = '# FF Arena — performance benchmark report';
$lines[] = '';
$lines[] = 'Generated: '.gmdate('c').' · PHP '.PHP_VERSION;
$lines[] = '';
$lines[] = '> Raw artifacts live in `storage/perf/` (outside git). This report is';
$lines[] = '> regenerated by `php scripts/perf/generate-report.php`.';
$lines[] = '';

/**
 * Render a latency stats block to markdown.
 */
function mdStats(array $stats): string
{
    return sprintf(
        'p50 **%s ms** · p90 **%s ms** · p95 **%s ms** · p99 **%s ms** · min %s · max %s (n=%d)',
        $stats['p50'] ?? '-',
        $stats['p90'] ?? '-',
        $stats['p95'] ?? '-',
        $stats['p99'] ?? '-',
        $stats['min'] ?? '-',
        $stats['max'] ?? '-',
        $stats['n'] ?? 0,
    );
}

foreach ($results as $name => $r) {
    $lines[] = '## '.$name;
    $lines[] = '';
    $lines[] = '- driver: `'.$r['driver'].'`';
    $lines[] = '- recorded at: '.$r['recorded_at'];

    if (isset($r['throughput_per_sec'])) {
        $lines[] = '- throughput: **'.$r['throughput_per_sec'].' registrations/sec**';
        $lines[] = '- ok: '.$r['ok'].' · failed: '.$r['failed'].' · waitlisted: '.$r['waitlisted'];
    }

    if (isset($r['replays'])) {
        $lines[] = '- idempotent replays: '.$r['replays'].' (verified events after replay: '.$r['verified_events_after_replay'].')';
    }

    $lines[] = '';

    if (isset($r['queries']) && is_array($r['queries'])) {
        $lines[] = '| Query | p50 | p90 | p95 | p99 | n |';
        $lines[] = '|---|---|---|---|---|---|';

        foreach ($r['queries'] as $label => $stats) {
            $lines[] = sprintf(
                '| %s | %s | %s | %s | %s | %d |',
                $label, $stats['p50'], $stats['p90'], $stats['p95'], $stats['p99'], $stats['n'],
            );
        }

        $lines[] = '';
    }

    if (isset($r['endpoints']) && is_array($r['endpoints'])) {
        $lines[] = '| Endpoint | p50 | p90 | p95 | p99 | ok | throttled | errors |';
        $lines[] = '|---|---|---|---|---|---|---|---|';

        foreach ($r['endpoints'] as $label => $v) {
            $s = $v['stats'];
            $lines[] = sprintf(
                '| %s | %s | %s | %s | %s | %d | %d | %d |',
                $label,
                $s['p50'],
                $s['p90'],
                $s['p95'],
                $s['p99'],
                $v['ok'] ?? 0,
                $v['throttled'] ?? 0,
                $v['errors'] ?? 0,
            );
        }

        $lines[] = '';
    }

    if (isset($r['service']) && isset($r['http'])) {
        $lines[] = '- service `standings()`: '.mdStats($r['service']);
        $lines[] = '- HTTP leaderboard: '.mdStats($r['http']).' (error '.$r['http_error_pct'].'%)';
        $lines[] = '';
    }

    if (isset($r['create']) && isset($r['verify'])) {
        $lines[] = '- createForTeam: '.mdStats($r['create']);
        $lines[] = '- verifyManually: '.mdStats($r['verify']);
        $lines[] = '- idempotent replay: '.mdStats($r['replay']);
        $lines[] = '';
    }

    if (isset($r['plans']) && is_array($r['plans']) && $r['plans'] !== []) {
        $lines[] = '### Query plans';
        $lines[] = '';

        foreach ($r['plans'] as $label => $plan) {
            $lines[] = '**'.$label.'**';
            $lines[] = '';
            $lines[] = '```';
            $lines[] = $plan;
            $lines[] = '```';
            $lines[] = '';
        }
    }
}

file_put_contents($outputPath, implode("\n", $lines)."\n");

// Machine-readable summary for CI.
$summary = [];

foreach ($results as $name => $r) {
    $summary[$name] = [
        'driver' => $r['driver'],
        'recorded_at' => $r['recorded_at'],
        'throughput_per_sec' => $r['throughput_per_sec'] ?? null,
        'error_pct' => $r['http_error_pct'] ?? ($r['endpoints'] ?? null),
    ];
}

file_put_contents($perfDir.'/summary.json', json_encode($summary, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)."\n");

echo "Report: {$outputPath}\n";
echo "Summary: {$perfDir}/summary.json\n";
echo 'Benchmarks found: '.implode(', ', array_keys($results))."\n";
